### PR TITLE
Support offline_access and fix consent issue

### LINKED ISSUE #2: If the scope contains 'offline_access' we also need to provide the device name
The device name is required when authenticating with a scope containing offline_access (which gets a refresh token). Currently the device is not added for offline_access, which breaks the authentication flow.

### PR DESCRIPTION
**Pull request by sandrinodimattia**
Fixes #2 and #4

### CODE REVIEW

File: Auth0Client/Auth0Client.cs [hunk 1]
```diff
@@ -13,32 +17,57 @@ namespace Auth0.SDK
...
+
+        private const string DeviceQueryString = "&device={0}";
         private const string ResourceOwnerEndpoint = "https://{0}/oauth/ro";
         private const string DelegationEndpoint = "https://{0}/delegation";
         private const string UserInfoEndpoint = "https://{0}/userinfo?access_token={1}";
         private const string DefaultCallback = "https://{0}/mobile";
 
-        private readonly string domain;
-        private readonly string clientId;
+        private readonly string _domain;
```
Comment (siacomuzzi) [inline Auth0Client/Auth0Client.cs]: We are trying to follow the StyleCop rules _(stylecop style omits the underscore and instead prefixes all class members with "this")_
